"""
Demo data for RescueMate.
Provides attractive, high-quality sample data for Adoptions, Rescues,
Found Pets, Community Reviews, and Platform Statistics.
"""

DEMO_ADOPTION_PETS = [
    {
        "id": "demo_pet_001",
        "name": "Buddy",
        "animal_type": "Dog",
        "breed": "Golden Retriever",
        "age": "2 years",
        "gender": "Male",
        "color": "Golden",
        "size": "Large",
        "personality": "Friendly, joyful, loves fetch & water play",
        "health_status": "Excellent",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "High",
        "description": "Buddy is a cheerful Golden Retriever with a heart of gold. Rescued during monsoon rains, he has blossomed into an affectionate, obedient companion who loves long park strolls and cuddling on rugs.",
        "special_needs": "None",
        "adoption_fee": "$75",
        "contact_info": "+91 98765 43210 (City Shelter)",
        "image_path": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-09-15"
    },
    {
        "id": "demo_pet_002",
        "name": "Luna",
        "animal_type": "Cat",
        "breed": "Calico Shorthair",
        "age": "1.5 years",
        "gender": "Female",
        "color": "Tricolor",
        "size": "Small",
        "personality": "Gentle purr machine, quiet & observant",
        "health_status": "Healthy",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "Medium",
        "description": "Luna is a delicate, sweet-tempered cat who loves warm sunbeams and feather wand toys. Fully litter trained and enjoys resting quietly beside you while you work or read.",
        "special_needs": "None",
        "adoption_fee": "$45",
        "contact_info": "+91 98765 43211 (Foster Care Network)",
        "image_path": "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-09-18"
    },
    {
        "id": "demo_pet_003",
        "name": "Max",
        "animal_type": "Dog",
        "breed": "German Shepherd",
        "age": "3 years",
        "gender": "Male",
        "color": "Black & Tan",
        "size": "Large",
        "personality": "Intelligent, loyal, alert & protective",
        "health_status": "Healthy & Vaccinated",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "High",
        "description": "Max is a majestic German Shepherd with exceptional intelligence. Leash trained, responds to basic voice commands, and would make an incredible devoted guardian for an active home.",
        "special_needs": "None",
        "adoption_fee": "$90",
        "contact_info": "+91 98765 43212 (Hope Animal Rescue)",
        "image_path": "https://images.unsplash.com/photo-1589941013453-ec89f33b5455?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-09-20"
    },
    {
        "id": "demo_pet_004",
        "name": "Milo",
        "animal_type": "Cat",
        "breed": "Orange Tabby",
        "age": "8 months",
        "gender": "Male",
        "color": "Ginger / White",
        "size": "Small",
        "personality": "Cuddly, vocal, curious & energetic",
        "health_status": "Healthy",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "Medium",
        "description": "Milo is a vibrant ginger kitten rescued with his siblings. He greets everyone at the door with soft chirps and loves curling up into a warm ball on your lap.",
        "special_needs": "None",
        "adoption_fee": "$40",
        "contact_info": "+91 98765 43213 (Paws & Whiskers)",
        "image_path": "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-09-22"
    },
    {
        "id": "demo_pet_005",
        "name": "Bella",
        "animal_type": "Dog",
        "breed": "Beagle",
        "age": "1 year",
        "gender": "Female",
        "color": "Tri-color",
        "size": "Medium",
        "personality": "Playful explorer, soulful eyes, gentle",
        "health_status": "Healthy",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "Medium",
        "description": "Bella has adorable floppy ears and an inquisitive nose. Rescued from abandonment, she is gentle with toddlers and loves afternoon nap sessions on plush blankets.",
        "special_needs": "None",
        "adoption_fee": "$65",
        "contact_info": "+91 98765 43214 (City Shelter)",
        "image_path": "https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-09-25"
    },
    {
        "id": "demo_pet_006",
        "name": "Snowy",
        "animal_type": "Dog",
        "breed": "Samoyed Mix",
        "age": "2.5 years",
        "gender": "Female",
        "color": "Pure White",
        "size": "Large",
        "personality": "Always smiling, calm, friendly & social",
        "health_status": "Excellent",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "Medium",
        "description": "Snowy is a fluffy white angel who looks like a walking cloud. Extremely polite, non-destructive, and loves meeting neighborhood friends on evening walks.",
        "special_needs": "Regular grooming required",
        "adoption_fee": "$80",
        "contact_info": "+91 98765 43215 (Northern Rescue Alliance)",
        "image_path": "https://images.unsplash.com/photo-1529429617124-95b109e86bb8?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-09-28"
    },
    {
        "id": "demo_pet_007",
        "name": "Thumper",
        "animal_type": "Rabbit",
        "breed": "Netherland Dwarf",
        "age": "10 months",
        "gender": "Male",
        "color": "Grey & White",
        "size": "Small",
        "personality": "Quiet, gentle, loves fresh timothy hay",
        "health_status": "Healthy",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "Low",
        "description": "Thumper is an indoor litter-box trained dwarf bunny. Docile, loves carrot treats and head pets, and makes an ideal gentle companion for apartment living.",
        "special_needs": "Indoor housing only",
        "adoption_fee": "$30",
        "contact_info": "+91 98765 43216 (Small Friends Sanctuary)",
        "image_path": "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-10-01"
    },
    {
        "id": "demo_pet_008",
        "name": "Cleo",
        "animal_type": "Cat",
        "breed": "Siamese Mix",
        "age": "2 years",
        "gender": "Female",
        "color": "Seal Point",
        "size": "Medium",
        "personality": "Affectionate, communicative, blue-eyed beauty",
        "health_status": "Healthy",
        "vaccination_status": "Up to Date",
        "spayed_neutered": "Yes",
        "good_with_kids": "Yes",
        "good_with_pets": "Yes",
        "energy_level": "Medium",
        "description": "Cleo has striking sapphire-blue eyes and a charming personality. She loves perching by windows watching birds and curling up under comforters at night.",
        "special_needs": "None",
        "adoption_fee": "$50",
        "contact_info": "+91 98765 43217 (Feline Friends)",
        "image_path": "https://images.unsplash.com/photo-1513360309081-38f0762daed1?auto=format&fit=crop&w=600&q=80",
        "created_at": "2026-10-03"
    }
]

DEMO_RESCUE_REPORTS = [
    {
        "id": "demo_rescue_001",
        "animal_type": "Dog",
        "breed": "Indie / Stray",
        "color": "Brown & White",
        "gender": "Male",
        "location": "Near MG Road Metro Flyover",
        "city": "Mumbai",
        "report_date": "2026-10-02",
        "description": "Young stray dog was found limping near traffic intersection. Rescue team dispatched within 40 minutes. Leg was splinted, now happily recovering at central care shelter.",
        "contact_name": "Rajesh Shinde",
        "contact_phone": "+91 98201 12345",
        "contact_email": "rajesh.rescue@gmail.com",
        "special_marks": "White patch over left eye",
        "condition": "Stable & Healing",
        "urgency": "high",
        "image_path": "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80"
    },
    {
        "id": "demo_rescue_002",
        "animal_type": "Cat",
        "breed": "Domestic Short Hair",
        "color": "Grey Tabby",
        "gender": "Female",
        "location": "Basement Parking, Lotus Enclave",
        "city": "Pune",
        "report_date": "2026-10-03",
        "description": "Mother cat with three 3-week-old kittens sheltered safely from rainy weather. Fostered by volunteer with warm bedding and veterinary formula.",
        "contact_name": "Sneha Kulkarni",
        "contact_phone": "+91 98902 67890",
        "contact_email": "sneha.foster@gmail.com",
        "special_marks": "Tabby swirl markings",
        "condition": "Healthy & Nursed",
        "urgency": "medium",
        "image_path": "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?auto=format&fit=crop&w=600&q=80"
    },
    {
        "id": "demo_rescue_003",
        "animal_type": "Dog",
        "breed": "Labrador Retriever",
        "color": "Golden Yellow",
        "gender": "Male",
        "location": "Shivaji Park Entrance 3",
        "city": "Mumbai",
        "report_date": "2026-10-04",
        "description": "Elderly, friendly Labrador was spotted disoriented near jogging track. Cleaned, fed, and housed in senior foster kennel while owner search is ongoing.",
        "contact_name": "Anand Varma",
        "contact_phone": "+91 98111 23456",
        "contact_email": "anand.varma@rescuemate.com",
        "special_marks": "Worn blue nylon collar, grey muzzle",
        "condition": "Safe & Comfortable",
        "urgency": "medium",
        "image_path": "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=600&q=80"
    },
    {
        "id": "demo_rescue_004",
        "animal_type": "Dog",
        "breed": "Mixed Breed Puppy",
        "color": "Black & Tan",
        "gender": "Female",
        "location": "Sector 21 Community Park",
        "city": "Navi Mumbai",
        "report_date": "2026-10-05",
        "description": "Dehydrated puppy found trapped in storm drain grating. Safely extracted by volunteers, received vet hydration fluids, now eating well and active.",
        "contact_name": "Dr. Meera Rao",
        "contact_phone": "+91 98450 98765",
        "contact_email": "meera.vet@gmail.com",
        "special_marks": "White paws",
        "condition": "Fully Recovered",
        "urgency": "low",
        "image_path": "https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=600&q=80"
    }
]

DEMO_FOUND_PETS = [
    {
        "id": "demo_found_001",
        "animal_type": "Dog",
        "breed": "Cocker Spaniel",
        "color": "Golden Honey",
        "gender": "Female",
        "location": "Rosewood Garden, Sector 15",
        "city": "Navi Mumbai",
        "report_date": "2026-10-04",
        "description": "Very friendly cocker spaniel found sitting by park gazebo. Wearing blue nylon collar with small bell. Trained, polite, eager to find owner.",
        "contact_name": "Pooja Nair",
        "contact_phone": "+91 98761 11223",
        "contact_email": "pooja.nair@gmail.com",
        "special_marks": "Blue bell collar, long wavy coat",
        "condition": "Excellent",
        "urgency": "medium",
        "image_path": "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=600&q=80"
    },
    {
        "id": "demo_found_002",
        "animal_type": "Cat",
        "breed": "Persian",
        "color": "Pure White",
        "gender": "Male",
        "location": "Greenfield Residency, Block B",
        "city": "Mumbai",
        "report_date": "2026-10-05",
        "description": "Fluffy white Persian cat found on corridor staircase. Clean and well-groomed. Being looked after by resident association until claimed.",
        "contact_name": "Rohan Mehta",
        "contact_phone": "+91 98222 33445",
        "contact_email": "rohan.mehta@gmail.com",
        "special_marks": "Green eyes, fluffy plume tail",
        "condition": "Healthy",
        "urgency": "low",
        "image_path": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=600&q=80"
    },
    {
        "id": "demo_found_003",
        "animal_type": "Dog",
        "breed": "Beagle Pup",
        "color": "Tricolor",
        "gender": "Male",
        "location": "Near City Bakery, West Street",
        "city": "Pune",
        "report_date": "2026-10-06",
        "description": "Playful young beagle found running around commercial square. Wearing red collar with paw pattern. Responding to whistle.",
        "contact_name": "Divya Joshi",
        "contact_phone": "+91 98333 44556",
        "contact_email": "divya.j@gmail.com",
        "special_marks": "Red paw collar, white tail tip",
        "condition": "Active & Safe",
        "urgency": "low",
        "image_path": "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=600&q=80"
    }
]

DEMO_COMMENTS = [
    {
        "id": "demo_comment_001",
        "user_name": "Priya Deshmukh",
        "message": "We adopted Luna through RescueMate last month! She has settled in so beautifully and brings endless joy to our home. Thank you team for making the process so transparent and easy! 🐾❤️",
        "created_at": "2026-10-05 14:30:00",
        "time_ago": "1 day ago"
    },
    {
        "user_name": "Karan Singhania",
        "message": "Reported an injured stray pup near Highway 48 yesterday. The local rescue volunteers coordinated within 30 minutes and picked him up for vet care. Truly grateful for this initiative! 🚑",
        "created_at": "2026-10-05 18:45:00",
        "time_ago": "1 day ago"
    },
    {
        "user_name": "Dr. Aarav Patel (Veterinarian)",
        "message": "As a partner vet, I love how RescueMate keeps detailed health records for all rescued animals. It makes ongoing vaccinations and follow-ups so much easier. Excellent work! 🩺",
        "created_at": "2026-10-06 09:15:00",
        "time_ago": "12 hours ago"
    },
    {
        "user_name": "Ananya Sen",
        "message": "Volunteered at the weekend adoption drive organized via this portal. 8 rescued pets found their forever homes! Proud to be part of this community. 🌟🐶",
        "created_at": "2026-10-06 12:20:00",
        "time_ago": "9 hours ago"
    },
    {
        "user_name": "Vikram Merchant",
        "message": "Donated blankets, puppy food, and medicine kits to the verified shelters listed on RescueMate. Keep up the inspiring work everyone! 🙌",
        "created_at": "2026-10-06 16:50:00",
        "time_ago": "4 hours ago"
    }
]

DEMO_ADMIN_STATS = {
    "total_users": 156,
    "found_pets": 18,
    "rescue_reports": 48,
    "active_reports": 66
}
