"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
from pathlib import Path
from dotenv import load_dotenv  # ✅ ADDED

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-g&@(c3()8z6_%edj9!b_@853ydzg6%7v4*gcu857^!30qpt0+8')

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'tanmaygaidhani.pythonanywhere.com']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myproject',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # ✅ ADDED FOR STATIC FILES
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': os.getenv('DATABASE_NAME', 'petrescue'),
        'CLIENT': {
            'host': os.getenv('MONGODB_URI'),
        }
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'   # ✅ UPDATED FOR INDIA

USE_I18N = True
USE_TZ = True


# STATIC FILES
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ✅ ADDED FOR PRODUCTION
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ✅ WHITENOISE CONFIG
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# MEDIA FILES
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ================= EMAIL =================
EMAIL_BACKEND = 'myproject.custom_email_backend.CustomEmailBackend'

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "s23_gaidhani_tanmay@mgmcen.ac.in"
EMAIL_HOST_PASSWORD = "jpwpzzdyqesmtyft"

DEFAULT_FROM_EMAIL = "RescueMate - Pet Adoption & Rescue Portal"
SERVER_EMAIL = DEFAULT_FROM_EMAIL


# ================= SECURITY (ADDED) =================
CSRF_TRUSTED_ORIGINS = ['https://tanmaygaidhani.pythonanywhere.com']

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
